version: '3.7'

services:
  db:
    image: postgres:9.6.17-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example      
    ports:
      - "5432"
  # imageboard-server:
    # build: .
    # ports:
      # - "5000"
      # - "5001"
    # volumes:
      # - .:/app      
